<?php
/**
 * ACF field group for block: {{BLOCK_NAME}}
 *
 * Auto-generated by WP MCP Toolkit. Do not edit manually.
 *
 * @package WP_MCP_Workspace
 */

defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}

acf_add_local_field_group( {{FIELD_GROUP_PHP}} );
